### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by elhilali-kamal** [Kaiji21/Game-PlantEd#1]
I have an issue in login after creating an account
![Screenshot 2024-02-13 223451](https://github.com/Kaiji21/Game-PlantEd/assets/101480438/bf4ede6f-3090-4928-ac99-a1a82219cb48)

**Comment by Kaiji21** [comment]
Hi Kamal,

Thank you for bringing this issue to our attention. We apologize for any inconvenience you've experienced. It appears that the "secret is not set" error is related to the JWT token used for authentication.
Please Ensure that the JWT secret key is correctly configured in the .env file of the Laravel project. It should be accessed using the config function in the Laravel code.
Example .env entry:
JWT_SECRET=your_secret_key_here

**Comment by elhilali-kamal** [comment]
Thanks it is working now
