### ISSUE TITLE
Button play now not working

### ISSUE THREAD

**Issue by elhilali-kamal** [Kaiji21/Game-PlantEd#2]
![image](https://github.com/Kaiji21/Game-PlantEd/assets/101480438/87dd1e5b-34c2-4c6f-ab52-0ae243ec397b)
Button play now redirect to google,com

**Comment by Kaiji21** [comment]
Hi Kamal,

Thank you for bringing this to our attention, and we appreciate your feedback. The issue you reported with the "Play Now" button redirecting to google.com seems unintended and unrelated to the educational game concept we aim to achieve in this repository.

The primary goal of this repository is to implement functionalities for an educational game, incorporating gamification concepts. The redirection to google.com is not intended behavior.
